version: "3.9"
services: 
    auth-service:
        build: 
            context: ./auth_service
            dockerfile: Dockerfile
        environment: 
            SERVER_PORT: "5000"
            REDIS_URL: "redis://redis/"
        depends_on: 
            - redis
        
    graphql-server:
        build: 
            # context: ./graphql_server
            # dockerfile: Dockerfile
            context: ./
            dockerfile: ./graphql_server/Dockerfile
        environment: 
            AUTH_SERVICE_URL: "http://auth-service:5000/"
            POSTGRES_URL: "postgres://taskery@postgres:5432/taskery?connect_timeout=10"
            GRAPHQL_SERVER_PORT: "5050"
        ports: 
            - "5050:5050"
        depends_on:
            - auth-service
            - postgres

    redis:
        restart: unless-stopped
        image: redis

    postgres:
        restart: unless-stopped
        image: postgres:12
        environment: 
            POSTGRES_DB: "taskery"
            POSTGRES_USER: "taskery"
            POSTGRES_HOST_AUTH_METHOD: "trust"  # we isolate db so nobody can access it 

